CREATE TABLE `system_monster` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(16) UNIQUE COMMENT '怪物名',
    `value` JSON COMMENT '数值配置',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置-怪物表';

CREATE TABLE `system_weapon` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(16) UNIQUE COMMENT '武器名',
    `value` JSON COMMENT '数值配置',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置-武器表';

CREATE TABLE `system_bullet` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(16) UNIQUE COMMENT '子弹名',
    `value` JSON COMMENT '数值配置',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置-子弹表';

CREATE TABLE `system_armor` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(16) UNIQUE COMMENT '防具名',
    `value` JSON COMMENT '数值配置',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置-防具表';
